

### PETER: MAKE BETTER VERSION OF STATE_TRANSTIION ###
### PETER+NAZIA: MAKE ACTION MODEL ###



#### READ EXAMPLE DATA ####

#### CREATE AGENT ####

#### GIVE AGENTS INPUTS TO TEST ####

#### FIT SINGLE AGENTMMODEL TO DATA AS TEST ####

#### FIT ENTIRE DATASET WITH MULTIPLE PARTICIPANTS AND STATISTICAL MODEL ####

